cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --nodes 1
    --cpus-per-task 1
    --mem-per-cpu 16G
    --partition pi_tsang
    --cpus-per-task={threads}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
jobs: 10
printshellcmds: True
use-conda: False
use-singularity: True
