configfile: "config.yaml"
singularity: "file:///gpfs/gibbs/pi/csei/users/lb2336/r_scripts/envs/Nicaragua/nicaragua.sif" 

rule all:    
    input:
        "data/output/UMAP.pdf",
        "data/output/individuals.pdf",
        "data/output/C3_STRD_AgeTrend.pdf",
        "data/output/C5_INF_AgeTrend.pdf",
        "data/output/sc_age_gene_set_enrichment_selected.pdf",
        "data/output/limma_fgsea_bubble_celltype_unspecific.pdf",
        "data/output/limma_fgsea_bubble_celltype_specific.pdf",
        "data/output/sc_FGCR_genes_age_trajectory.pdf",
        "data/output/sc_AntigenPresentation_genes_age_trajectory.pdf",
        "data/output/sc_TLR_genes_age_trajectory.pdf",
        "data/output/sc_CellCycle_genes_age_trajectory.pdf",
        "data/output/VES_Heatmap.pdf",
        "data/output/Bcell_cluster_top40.pdf",
        "data/output/Tcell_cluster_top40.pdf",
        "data/output/NKcell_cluster_top40.pdf",
        "data/output/Monocyte_cluster_top40.pdf",
        "data/output/signature_stability_heatmap.pdf",
        "data/output/IAB-Bcell-stability_trend.pdf",
        "data/output/IFN-stability_trend.pdf",
        "data/output/CD8_VM_GPR56hi-stability_trend.pdf",
        "data/output/AdultOld_Age_Correlations.pdf",
        "data/output/Adult_Age_Correlations_TopGenes.pdf",
        "data/output/Old_Age_Correlations_TopGenes.pdf",
        "data/output/AdultOld_Age_Correlations_Boxplot.pdf",
        "data/output/IFN-stability_trend_explicit_monocytes.pdf",
        "data/output/IFN-stability_trend_explicit_monocytes_genes.pdf"

rule VES_Heatmap:
    input:
        "data/input/paper_supplementary_tables/supp_tables_S10.csv",
        "data/input/paper_supplementary_tables/supp_tables_S9.csv",
        "data/input/variance_partition_results/NICA_batch2to4_new_timepoints_fsex_subject_enriched_with_labels.rds",
        "data/input/variance_partition_results/NICA_batch2to4_new_timepoints_cleaned_normalized_fsex_vpars_object.rds",
        "data/input/heritability/inheritability_data_pvals.csv",
        "data/input/heritability/inheritability_data_777.csv"
    output:
        "data/output/VES_Heatmap.pdf",
        "data/output/Bcell_cluster_top40.pdf",
        "data/output/Tcell_cluster_top40.pdf",
        "data/output/NKcell_cluster_top40.pdf",
        "data/output/Monocyte_cluster_top40.pdf",
        "data/output/signature_stability_heatmap.pdf",
        "data/output/IAB-Bcell-stability_trend.pdf",
        "data/output/IFN-stability_trend.pdf",
        "data/output/CD8_VM_GPR56hi-stability_trend.pdf",
        "data/output/IFN-stability_trend_explicit_monocytes.pdf",
        "data/output/IFN-stability_trend_explicit_monocytes_genes.pdf"
    script:
        "scripts/VES_Heatmap.R"


rule Age_trends_and_enrichments:
    input:
        "data/input/paper_supplementary_tables/supp_tables_S6.csv",
        "data/input/paper_supplementary_tables/supp_tables_S10.csv",
        "data/input/variance_partition_results/NICA_batch2to4_new_timepoints_cleaned_normalized_fsex_vpars_object.rds",
        "data/input/linear_model_results/NICA_batch2to4_new_timepoints_cleaned_normalized_fsex_spline.rds",
        "data/input/pseudobulk/NICA_batch2to4_new_timepoints_cleaned_normalized.rds"
    output:
        "data/output/C3_STRD_AgeTrend.pdf",
        "data/output/C5_INF_AgeTrend.pdf",
        "data/output/sc_age_gene_set_enrichment_selected.pdf",
        "data/output/limma_fgsea_bubble_celltype_unspecific.pdf",
        "data/output/limma_fgsea_bubble_celltype_specific.pdf",
        "data/output/sc_FGCR_genes_age_trajectory.pdf",
        "data/output/sc_AntigenPresentation_genes_age_trajectory.pdf",
        "data/output/sc_TLR_genes_age_trajectory.pdf",
        "data/output/sc_CellCycle_genes_age_trajectory.pdf"
    script:
        "scripts/Age_trends_and_enrichments.R"


rule AdultOldCorrelations:
    input:
        "data/input/variance_partition_results/age_subject_variance_VESlist_adult_old_aging_cohort_renorm.RDS",
        "data/input/gene_sets/age_subject_variance_ultrastab.RDS",
        "data/input/variance_partition_results/NICA_batch2to4_new_timepoints_cleaned_normalized_fsex_vpars_object_renorm.rds"
    output:
        "data/output/AdultOld_Age_Correlations.pdf",
        "data/output/Adult_Age_Correlations_TopGenes.pdf",
        "data/output/Old_Age_Correlations_TopGenes.pdf",
        "data/output/AdultOld_Age_Correlations_Boxplot.pdf"
    script:
        "scripts/AdultOldCorrelations_new.R"

rule individuals_and_UMAP:
    input:
        "data/input/seurat_object/NICAall_combined_manual_labeled_cleaned_final.rds", 
    output:
        "data/output/UMAP.pdf",
        "data/output/individuals.pdf"
    script:
        "scripts/Individuals_and_UMAP.R"

