---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ImmuneAgeStability)
```


```{r}
### baseline immune response signatures
print("baseline immune response signatures")
print(names(baseline_signatures))

### age trajectories
print("age trajectories")
print(names(age_trajectories))

### stable genes
print("stable genes")
print(names(stable_genes))

```


```{r}
stability_df<-compute_signature_stability(signature = baseline_signatures$TGSig)
plot_signature_stability(signature_name = "TGSig",signature_stability_df = stability_df)
```

```{r}
stability_slope_df<-compute_signature_stability_slope(signature_name = "IFN", signature = baseline_signatures$IFN)
plot_signature_stability_radar(stability_slope_df)
```

```{r}
stability_rateOfchange_df<-compute_signature_stability_rateofchange(signature_name = "IFN", signature = baseline_signatures$IFN)
plot_signature_agetrend(signature_rateOfchange = stability_rateOfchange_df,cell_subsets = c("Mono_Classical","Mono_NonClassical","bulk"))
```

```{r}
stability_rateOfchange_df<-compute_signature_stability_rateofchange(signature_name = "IFN - genes", signature = age_trajectories$`IFN genes`)
plot_signature_gene_agetrend(signature_rateOfchange = stability_rateOfchange_df,cell_subsets = c("Mono_Classical"))
```
