---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(stats)
library(matrixStats)
```

```{r}
### Aging cohort: Adult / Old correlations

#load bootstrapped variance partition of adult cohort
#adults: bootstraps[[1-10]], #old bootstraps[[11-20]]
nind_list<-readRDS("/Users/leon/Documents/NICA/sc_analysis/data/age_subject_variance_VESlist_adult_old_aging_cohort.RDS")
ultrastab<-readRDS("/Users/leon/Documents/NICA/sc_analysis/data/age_subject_variance_ultrastab.RDS")
ultrastab_clust_vpars<-readRDS("/Users/leon/Documents/NICA/sc_analysis/data/NICA_batch2to4_new_timepoints_cleaned_normalized_fsex_vpars_object.rds")

age_corr_list<-list()
age_corrp_list<-list()

for (ct in names(nind_list)){
  print(ct)
  ultra<-ultrastab[[ct]]
  if (ct=="Monocytes"){
    ct.sub<-c("Mono_Classical","Mono_NonClassical")
  } else if (ct=="Bcells"){
    ct.sub<-c("B_Naive","B_Mem")
  } else if (ct=="NKcells"){
    ct.sub<-c("NK_CD16hi","NK_CD56hi")
  } else if (ct=="Tcells_CD4"){
    ct.sub<-c("CD4_Naive","CD4_Mem")
  } else if (ct=="Tcells_CD8"){
    ct.sub<-c("CD8_Naive","CD8_Mem")
  }
  for (age in c("Adult","Old")){
   print(age)
   pseudo.sce.list<-nind_list[[ct]]
   nind_markers<-rownames(pseudo.sce.list[[11]])
   #adults: bootstraps[[1-10]], #old bootstraps[[11-20]]
   if (age=="Adult"){
      idxs<-seq(1,10)
   } else if (age=="Old"){
      idxs<-seq(11,20)
   }
   df_nind<-as.data.frame(cbind(pseudo.sce.list[[idxs[1]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[2]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[3]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[4]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[5]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[6]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[7]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[8]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[9]]][nind_markers,"Donor_id"],pseudo.sce.list[[idxs[10]]][nind_markers,"Donor_id"]))
   rownames(df_nind)<-nind_markers
   colnames(df_nind)<-c("A","B","C","D","E","F","G","H","I","J")
   df_nind<-rowMedians(as.matrix(df_nind))
   names(df_nind)<-nind_markers
   df_nind<-df_nind[which(!is.na(df_nind))]
   df_nind_adult<-df_nind
    
   ultrastab_clust_vpars_ct<-ultrastab_clust_vpars[ultrastab_clust_vpars$celltype==ct.sub[1] | ultrastab_clust_vpars$celltype==ct.sub[2],]
   ultrastab_clust_vpars_ct<-as.data.frame(ultrastab_clust_vpars_ct %>% group_by(gene) %>% summarize(max(subject_variance_explained)))
   colnames(ultrastab_clust_vpars_ct)<-c("gene","subject_variance_explained")
   rownames(ultrastab_clust_vpars_ct)<-ultrastab_clust_vpars_ct$gene
   ultrastab_clust_vpars_ct<-ultrastab_clust_vpars_ct[nind_markers,]
   ultrastab_clust_vpars_ct<-ultrastab_clust_vpars_ct[which(!is.na(ultrastab_clust_vpars_ct[,1])),]
   df_nind<-ultrastab_clust_vpars_ct$subject_variance_explained
   names(df_nind)<-ultrastab_clust_vpars_ct$gene
   df_nind_young<-df_nind
   df_nind_adult<-df_nind_adult[names(df_nind_young)]
   df_nind_young<-df_nind_young[!is.na(df_nind_adult)]
   df_nind_adult<-df_nind_adult[!is.na(df_nind_adult)]
   df_nind<-as.data.frame(cbind(df_nind_adult,df_nind_young))
   colnames(df_nind)<-c("adult","young")
   test<-cor.test(df_nind$adult, df_nind$young,method = "spearman")
   ptest<-cor.test(df_nind$adult, df_nind$young)
   mod <- lm(df_nind$adult ~ df_nind$young + 0)
   cf <- coef(mod)

   df_nind$age_group<-age
   df_nind$pval<-test$p.value
   df_nind$corr<-as.vector(test$estimate)
   df_nind$celltype<-ct
   df_nind$ultra<-"normal"
   df_nind$gene<-rownames(df_nind)
   df_nind$ultra[df_nind$gene %in% ultra]<-"ultrastab"
   age_corr_list[[paste0(ct,"-",age)]]<-df_nind
   age_corrp_list[[paste0(ct,"-",age)]]<-c(as.vector(test$estimate),test$p.value,ptest$estimate,as.numeric(cf[1]),ct,age)
  }
}
age_corr_list_df<-do.call(rbind,age_corr_list)
age_corrp_list_df<-as.data.frame(do.call(rbind,age_corrp_list))
colnames(age_corrp_list_df)<-c("rho","p-val","pearson","slope","celltype","age")
age_corr_list_df$ct_age_grp<-paste0(age_corr_list_df$celltype,"-",age_corr_list_df$age_group)
age_corr_list_df$ct_age_grp_fct<-factor(age_corr_list_df$ct_age_grp,levels=c("Bcells-Adult","Monocytes-Adult","NKcells-Adult","Tcells_CD4-Adult","Tcells_CD8-Adult","Bcells-Old","Monocytes-Old","NKcells-Old","Tcells_CD4-Old","Tcells_CD8-Old"))
ggplot(data=age_corr_list_df[age_corr_list_df$ultra=="normal",],aes(y=adult,x=young)) + geom_point(colour="black") + geom_density_2d(bins=150) + geom_abline(intercept = 0, slope = 1) + geom_point(data=age_corr_list_df[age_corr_list_df$ultra=="ultrastab",],aes(y=adult,x=young), colour="red") + geom_smooth(method="lm",formula=y~x+0, se=F, lty=2, color="orange", lwd=1) + facet_wrap(vars(ct_age_grp_fct),nrow = 2) + theme_light()
```

```{r}
### Aging cohort: Young / Adult / Old VES boxplots

age_corr_list_df_ed<-readRDS("/Users/leon/Documents/NICA/sc_analysis/data/age_subject_variance_young_adult_old.RDS")
ggplot(data=age_corr_list_df_ed[(age_corr_list_df_ed$ultra=="ultrastab"),],aes(x=celltype,y=adult,fill=age_group))+geom_boxplot()+theme_bw() + geom_point(shape=1, position = position_jitterdodge(jitter.width = 0.1), alpha=0.25) + ylab("VES [ultrastable genes]")
```


```{r}
#adult cohort raw count data loading example myecells
sce <- readH5AD("/gpfs/gibbs/pi/csei/users/lb2336/download/Adult_scAging_study/all_pbmcs/all_pbmcs_rna_harmony.h5ad")
sce.seurat <- as.Seurat(sce[,sce$Cluster_names=="Myeloid cells"], counts = "X", data = "X") # sce$Cluster_names=="TRAV1-2- CD8+ T cells"
sce.raw <- readH5AD("/gpfs/gibbs/pi/csei/users/lb2336/download/Adult_scAging_study/raw_counts_h5ad/pbmc_gex_raw_with_var_obs.h5ad", use_hdf5 = TRUE)
sce.mye <- sce.raw[,sce.raw$Cluster_names=="Myeloid cells"]
assay(sce.mye, "X") <- as.matrix(assay(sce.mye, "X"))
sce.seurat.mye <- as.Seurat(sce.mye, counts = "X", data = "X")
sce.seurat.mye$Donor_id<-sce.seurat$Donor_id
sce.seurat.mye$Batch<-sce.seurat$Batch
sce.seurat.mye$Age<-sce.seurat$Age
sce.seurat.mye$Sex<-sce.seurat$Sex


#adult cohort pseudobulk loop example myecells
donors<-readRDS("/gpfs/gibbs/pi/csei/users/lb2336/signatures/age_subject_variance_donors_adult_old_aging_cohort.RDS")
for (batch in seq(1,20)){
    print(batch)
    d<-donors[[batch]]
    DGELISTS_OUT_PATH <- paste0("/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/aging_cohort/adults_myecells_",batch,".rds")

    #Parameters for pseudobulk pooling
    LIBSIZE_FILTER <- 0
    MIN_CELLS_PER_POOL <- 5
    MIN_SAMPLES_PER_CELLTYPE <- 15
    #Cell annotation column
    CELL_ANNOTATION_COLUMN <- "orig.ident"
    #read in data
    seurat_obj <- sce.seurat.mye[,sce.seurat.mye$Donor_id %in% d]
    meta <- seurat_obj@meta.data
    meta$barcodes<-colnames(seurat_obj)
    rna <- GetAssayData(seurat_obj, assay = "originalexp", slot = "counts")
    sample_cols <- c("Donor_id", "Age", "Sex", "Batch")
    sample_cols <- c(sample_cols, CELL_ANNOTATION_COLUMN)
    samples <- paste(meta$Donor_id, meta$Age, meta$Batch, sep = "_")
    
    pseudobulk_list <- getPseudobulkList(mat = rna, celltypes = meta[[CELL_ANNOTATION_COLUMN]], 
                                         meta = meta,
                                         samples = samples, 
                                         min_cells_per_pool = MIN_CELLS_PER_POOL, 
                                         min_samples_per_celltype = MIN_SAMPLES_PER_CELLTYPE,
                                         barcode_col_name = "barcodes", 
                                         sample_level_meta_cols = sample_cols,
                                         #cell_level_meta_cols = cell_cols, 
                                         pooling_function = "sum",
                                         output_type = "DGEList")
    
    pseudobulk_list <- lapply(pseudobulk_list, function(dge){
      dge[, dge$samples$lib.size > LIBSIZE_FILTER]
      
  })
  
  n_samples_per_celltype <- sapply(pseudobulk_list, ncol)
  print("n_samples_per_celltype before final filtering")
  print(n_samples_per_celltype)
  
  pseudobulk_list <- pseudobulk_list[n_samples_per_celltype > MIN_SAMPLES_PER_CELLTYPE]
  
  saveRDS(pseudobulk_list, DGELISTS_OUT_PATH)
}
```

```{r}
#adult cohort pseudobulk normalization loop

var.threshold <- 1
pseudobulk_list_normalized <- list()

for (i in list.files("/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/aging_cohort/",pattern="adults")){
  cat(i,"-\n")
  path<-paste0("/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/aging_cohort/",i)
  eset <- readRDS(path)$SeuratProject
  geneExpr <- eset$counts
  sample.info <- eset$samples
  sample.info$sample.id <- paste0(sample.info$Donor_id,".",sample.info$Age)
  
  # filter out lowly expressed genes
  cat("Number of genes with no counts across samples:\n")
  print(table(rowSums(eset$counts==0)==nrow(sample.info)))
  keep.exprs <- filterByExpr(eset,group = sample.info$Sex, min.count = 2,min.prop=0.5)
  cat("Number of genes to keep by expr:",sum(keep.exprs),"\n")
  eset <- eset[keep.exprs,,keep.lib.sizes = F]
 
  # stage 1: normalize and correct
  eset <- calcNormFactors(eset)
  sample.info$Sex <- ifelse(is.na(sample.info$Sex),"Control",as.character(sample.info$Sex))
  # a model that accommodate the control samples
  tmp.model <- model.matrix(~ 0 + Batch,sample.info)
  vobj <- voom(eset ,design = tmp.model,plot = F)
  #title("",i)
  geneExpr <- vobj$E # normalized
  
  # PCA using baseline samples before correction
  baseline.samples <- sample.info
  baseline.geneExpr <- geneExpr[,rownames(baseline.samples)]
  baseline.geneExpr.pca <- prcomp(t(baseline.geneExpr),center = T,scale. = T)
  baseline.samples <- cbind(baseline.samples,baseline.geneExpr.pca$x[rownames(baseline.samples),1:2])
  print(ggplot(baseline.samples,aes(PC1,PC2)) + geom_point(aes(color=paste0(Batch),shape=Donor_id == "Control"),size=2,alpha=0.8) + 
          ggtitle(paste0("Before correction: ",i)))
  cat("Before correction:\n")
  print(car::Anova(lm(PC1 ~ n_barcodes + Batch,baseline.samples)))
  print(car::Anova(lm(PC2 ~ n_barcodes + Batch,baseline.samples)))
  
  # remove batch effect
  normalized.expr.batch.effect <- removeBatchEffect(geneExpr, batch = eset$samples$Batch, 
                                                    covariates = eset$samples$n_barcodes,
                                                    design = tmp.model)
  geneExpr <- normalized.expr.batch.effect
  eset$normalizedExpr <- geneExpr
  pseudobulk_list_normalized[[i]] <- eset
}
saveRDS(pseudobulk_list_normalized,"/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/aging_cohort/all_adult_pbulk_list_normalized.rds")
```

```{r}
#adult cohort pseudobulk variance partition loop

all_tts_vpar<-list()
for (a in c("all_adult_pbulk_list_normalized")){
  print(a)
  DGE.IN.PATH <- paste0("/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/aging_cohort/",a,".rds")

  # Output Paths ----------------------------------------------------
  FIT.OUT.PATH <- "/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/limma_fit_no_subj_elspline_8knot_fit_fsex.rds"
  SPLINE.DESIGN.OUT.PATH <- "/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/limma_fit_no_subj_elspline_8knot_spline_design_fsex.rds"
  TT.OUT.PATH <- "/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/limma_fit_no_subj_elspline_8knot_toptab_anova_fsex.csv"

  all_tts_bcells_vpar<-list()
  all_tts_nkcells_vpar<-list()
  all_tts_myecells_vpar<-list()
  all_tts_tcellscd4_vpar<-list()
  all_tts_tcellscd8_vpar<-list()

  # Read in data ----------------------------------------------------
  dge_a <- readRDS(DGE.IN.PATH)
  for (c in names(dge_a)) { #
    print(c)
    dge <- dge_a[[c]]

    # remove controls -------------------------------------------------
    dge <- dge[, !is.na(dge$samples$Age)]


    # make things factors ---------------------------------------------
    meta <- dge$samples
    meta$Donor_id <- factor(meta$Donor_id)
    meta$Age <- factor(meta$Age)
    meta$Age <- as.numeric(meta$Age)*12
    meta$Batch <- factor(meta$Batch)

    print("fit simplified age model")
    form <- ~ (1|Donor_id) + Age + (1 | Batch)
    vobjDream = voomWithDreamWeights( dge, form, meta, suppressWarnings=TRUE)
    fitmm = dream( vobjDream, form, meta)
    tt <- topTable(fitmm, "Age", number = Inf)
    tt$gene<-rownames(tt)

    idx<-as.numeric(str_split_i(str_split_i(c,"_",-1),"\\.",1))
    if(grepl("bcells",c)){
      tt$cell.type<-"Bcells"
      all_tts_bcells_vpar[[idx]]<-tt
    } else if (grepl("nkcells",c)){
      tt$cell.type<-"NKcells"
      all_tts_nkcells_vpar[[idx]]<-tt
    } else if (grepl("mye",c)){
      tt$cell.type<-"Monocytes"
      all_tts_myecells_vpar[[idx]]<-tt
    } else if (grepl("cd4",c)){
      tt$cell.type<-"Tcells_CD4"
      all_tts_tcellscd4_vpar[[idx]]<-tt
    } else if (grepl("cd8",c)){
      tt$cell.type<-"Tcells_CD8"
      all_tts_tcellscd8_vpar[[idx]]<-tt   
    } 
  }
  all_tts_vpar[["Bcells"]]<-all_tts_bcells_vpar
  all_tts_vpar[["NKcells"]]<-all_tts_nkcells_vpar
  all_tts_vpar[["Monocytes"]]<-all_tts_myecells_vpar
  all_tts_vpar[["Tcells_CD4"]]<-all_tts_tcellscd4_vpar
  all_tts_vpar[["Tcells_CD8"]]<-all_tts_tcellscd8_vpar
}
saveRDS(all_tts_vpar,"Documents/NICA/sc_analysis/data/age_subject_variance_VESlist_adult_old_aging_cohort.RDS")
```