---
title: "Individuals, Timepoints and single cell UMAP"
output: html_notebook
---


```{r}
# set seed
set.seed(4)

# load libraries
library(Seurat)
library(harmony)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r}
# load single cell seurat object
dataset.query <- readRDS("NICAall_combined_manual_labeled_cleaned_final.rds")
prots<-rownames(dataset.query)[!(str_detect(rownames(dataset.query),"iso")|str_detect(rownames(dataset.query),"Iso"))]
dataset.query <- dataset.query[prots,]
dataset.query <- dataset.query[,dataset.query$manual.cid!="doublets"]
```

```{r}
# vizualize UMAP
Idents(dataset.query)<-dataset.query$manual.cid
dataset.query <- FindVariableFeatures(dataset.query, selection.method = "vst", nfeatures = 2000)
dataset.query <- ScaleData(dataset.query)#, vars.to.regress = "batch")
dataset.query <- RunPCA(dataset.query, features = VariableFeatures(object = dataset.query))
#dataset.query.harmonized <- dataset.query
dataset.query.harmonized <- RunHarmony(dataset.query, "batch")
dataset.query.harmonized <- FindNeighbors(dataset.query.harmonized, dims = 1:15, reduction="harmony", features=VariableFeatures(dataset.query.harmonized))
dataset.query.harmonized <- FindClusters(dataset.query.harmonized, resolution = 1, features=VariableFeatures(dataset.query.harmonized))
dataset.query.harmonized <- RunUMAP(dataset.query.harmonized, dims=1:15, reduction = "harmony") #batch3, n.neighbors = 5L, min.dist = 0.3 #batch4 dims=1:15 #all dims=1:15
DimPlot(dataset.query.harmonized, reduction = "umap", group.by = "manual.cid", label = TRUE, repel = TRUE, raster=FALSE, label.size = 4, shuffle = TRUE)
```

```{r}
# aggregate celltypes, individuals, gender and timepoints
nica_list <- list()
for (i in unique(dataset.query$matched.individual)){
  print(i)
  dataset.i<-dataset.query[,which(dataset.query$matched.individual==i)]
  for (t in unique(dataset.i$matched.timepoint.age[which(!is.na(dataset.i$matched.timepoint.age))])){
    dataset.t<-dataset.i[,which(dataset.i$matched.timepoint.age==t)]
    b<-unique(dataset.t$batch)
    g<-unique(dataset.t$gender)
    nica_list[[paste0(i,"_",t,"_",b,"_",g)]]<-table(dataset.t$manual.cid)
  }
}

nica.celltypes<-as.data.frame(do.call(cbind, nica_list))
nica.celltypes<-data.frame(t(nica.celltypes))
nica.celltypes.sums<-rowSums(nica.celltypes,na.rm = TRUE)
for (t in seq(1,dim(nica.celltypes)[1])) {
  nica.celltypes[t,]<-nica.celltypes[t,]/nica.celltypes.sums[t]
}
nica.celltypes$sums<-nica.celltypes.sums
nica.celltypes$individual<-as.vector(t(data.frame(sapply(rownames(nica.celltypes),function(x){str_split(x,"_")[[1]]})))[,1])
nica.celltypes$timepoint<-as.vector(t(data.frame(sapply(rownames(nica.celltypes),function(x){str_split(x,"_")[[1]]})))[,2])
nica.celltypes$timepoint<-as.numeric(nica.celltypes$timepoint)#*12
nica.celltypes$batch<-as.vector(t(data.frame(sapply(rownames(nica.celltypes),function(x){str_split(x,"_")[[1]]})))[,3])
nica.celltypes$gender<-as.vector(t(data.frame(sapply(rownames(nica.celltypes),function(x){str_split(x,"_")[[1]]})))[,4])
```

```{r}
#visualize distribution of timepoints per individual
age_df<-nica.celltypes[c("individual","timepoint","gender")]
age_df<-age_df[age_df$individual!="nica4416",]
age_df<-age_df %>% group_by(individual,gender) %>% summarise_at(vars(timepoint),list(max = max, min=min))
age_df<-as.data.frame(age_df)
age_df$V3<-age_df$max - age_df$min
age_df<-age_df[order(age_df$V3, decreasing = T),]
age_df$idx<-seq(1,15)
age_df %>%
    ggplot(aes(x = idx, col=gender)) +
    geom_linerange(aes(ymin = min, ymax = max, x = idx),
                   size = 1.5, alpha = 0.25) +
    geom_point(aes(y = min)) +
    geom_point(aes(y = max)) +
    coord_flip() +
    ylab("Followed age range") +
    theme_bw(base_size = 15) +
    theme(axis.title.y = element_blank(), legend.position = c(0.8, 0.85), legend.background = element_rect(fill = NA)) + scale_y_continuous(breaks = seq(3,17,2))+ scale_x_continuous(breaks = seq(1,15,1)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), legend.title=element_text(size=14))
```