---
title: "Heatmap - subject variability of highly subject specific functional genes"
output: html_notebook
---


```{r}
# set seed
set.seed(4)

# load libraries
library(Seurat)
library(pheatmap)
library(stringr)
library(patchwork)
library(viridis)
library(circlize)
library(dplyr)
library(ggplot2)
library(reshape2)
library(fmsb)
library(scales)

# load data
nrchd_gene_df<-read.csv("/home/lb2336/project/NICA/supp_tables_S10.csv") # bulk rna enriched genesets
bulk_subj_var_gene_df<-read.csv("/home/lb2336/project/NICA/supp_tables_S9.csv") # bulk rna subject variance
rownames(bulk_subj_var_gene_df)<-bulk_subj_var_gene_df$Gene
enrichment_df<-readRDS("/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/NICA_batch2to4_new_timepoints_fsex_subject_enriched_with_labels.rds") # single cell rna enriched genesets
enrichment_df<-enrichment_df[str_detect(enrichment_df$pathway,"btm"),]
vpars<-readRDS("/gpfs/gibbs/pi/csei/users/lb2336/pseudo_bulk/NICA_batch2to4_new_timepoints_cleaned_normalized_fsex_vpars_object.rds") # single cell gene-wise variance partition
inh<-read.csv("/home/lb2336/project/NICA/inheritability_data_pvals.csv") # hertability data of gene expression (Wright et al 2014, Nat Genet.)
inh777<-read.csv("/home/lb2336/project/NICA/inheritability_data_777.csv")
inh777<-inh777$X
inh777<-inh[which(inh$probe.id %in% inh777),]$gene.symbol
inh_grouped<-inh %>% group_by(gene.symbol) %>% summarize(h2_max=max(h2))
inh_grouped <- as.data.frame(inh_grouped)
rownames(inh_grouped) <- inh_grouped$gene.symbol
```

```{r}
# adapt loaded geneset list
genesetl<-list()
for (i in seq(1,nrow(nrchd_gene_df))){
  gset<-unlist(str_split(nrchd_gene_df$leadingEdge[i]," "))
  genesetl[[paste(str_split(nrchd_gene_df$pathway[i],"_")[[1]][2:3],collapse="_")]]<-gset
}


# reformat subject variance data
ledge<-unique(unlist(enrichment_df$leadingEdge))
vpars_h<-vpars[c("subject_variance_explained","celltype","gene")]
vpars_h<-vpars_h[which(!(vpars_h$celltype %in% c("ILC","doublets"))),]
vpars_h<-reshape(vpars_h, idvar = "gene", timevar = "celltype", direction = "wide")
vpars_h[is.na(vpars_h)]<-0
genes<-vpars_h$gene
vpars_h<-vpars_h[which(colnames(vpars_h)!="gene")]
vpars_h<-sapply(vpars_h, as.numeric)
row.names(vpars_h)<-genes
colnames(vpars_h)<-as.vector(sapply(colnames(vpars_h),function(x){str_split_i(x,"\\.",2)}))
vpars_h<-vpars_h[which(rownames(vpars_h) %in% unlist(ledge)),]


# collect and reformat heatmap annotations
ledge_list<-list()
for (pway in unique(enrichment_df$pathway)){ 
  ledge<-unique(unlist(enrichment_df[which(enrichment_df$pathway==pway),]$leadingEdge))
  pway<-str_split_i(pway,"btm_",2)
  ledge_list[[pway]]<-ledge
}

#leading edge genes from bulk enriched pathways
p_annot_l<-list()
for (p in names(ledge_list)){
    p_annot<-as.numeric(rownames(vpars_h) %in% ledge_list[[p]])
    if(str_detect(p,"M61") | str_detect(p,"M7.2")){
      p_annot<-as.numeric(rownames(vpars_h) %in% ledge_list[["M61.0_enriched in NK cells (II)"]] | rownames(vpars_h) %in% ledge_list[["M7.2_enriched in NK cells (I)"]])
      p="M7.2_M61_enriched in NK cells (I/II)"
    }
    if(str_detect(p,"M11") | str_detect(p,"M118")){
      p_annot<-as.numeric(rownames(vpars_h) %in% ledge_list[["M11.0_enriched in monocytes (II)"]] | rownames(vpars_h) %in% ledge_list[["M118.0_enriched in monocytes (IV)"]])
      p="M11_M118_enriched in monocytes (II/IV)"
    }
    if(str_detect(p,"M69") | str_detect(p,"M47") | str_detect(p,"M47.2")){
      p_annot<-as.numeric(rownames(vpars_h) %in% ledge_list[["M47.0_enriched in B cells (I)"]] | rownames(vpars_h) %in% ledge_list[["M47.2_enriched in B cells (III)"]] | rownames(vpars_h) %in% ledge_list[["M69_enriched in B cells (VI)"]])
      p="M47_M47.2_M69_enriched in B cells (I/III/VI)"
    }
    if(str_detect(p,"M2.0") | str_detect(p,"M2.1")){
      p_annot<-as.numeric(rownames(vpars_h) %in% ledge_list[["M2.0_extracellular matrix (I)"]] | rownames(vpars_h) %in% ledge_list[["M2.1_extracellular matrix (II)"]])
      p="M2.0_M2.1_extracellular matrix (I/II)"
    }

    p_annot_l[[p]]<-p_annot
}
p_annot_l<-as.data.frame(do.call(cbind,p_annot_l))
rownames(p_annot_l)<-rownames(vpars_h)

#inheritable gens
p_annot<-as.numeric(rownames(vpars_h) %in% inh777)
p_annot_l$"HERITABILITY (Wright et al.,Nature Genetics 2014)"<-p_annot
p_annot_l$"HERITABILITY (continuous h2 value)"<-inh_grouped[rownames(p_annot_l),]$h2_max #

#clusterID
p<-pheatmap(t(vpars_h), scale="none", clustering_distance_cols="correlation", cutree_cols = 4, silent = T)

# cut heatmap tree
p_annot_l$clusterid<-cutree(p$tree_col, k = 4)
```

```{r}
library(ComplexHeatmap)

col_fun = colorRamp2(c(-0.5, 0, 1), c("blue", "#EBEBEB", "red"))
col_fun1 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "red"))
col_fun2 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "green"))
col_fun3 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "violet"))
col_fun4 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "purple"))
col_fun5 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "turquoise"))
col_fun6 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "orange"))
col_fun7 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "magenta"))
col_fun8 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "brown"))
col_fun9 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "coral"))
col_fun10 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "darkgreen"))
col_fun11 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "lightblue"))
col_fun12 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "salmon"))
col_fun13 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "gold"))
col_fun14 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "burlywood"))
col_fun15 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "aquamarine"))
col_fun16 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "darkorange"))
col_fun17 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "blue"))
col_fun18 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "black"))
col_fun19 = colorRamp2(c(-0.5, 0, 1), c("black", "#EBEBEB", "darksalmon"))

col_list<-list("HERITABILITY (continuous h2 value)"=col_fun,"HERITABILITY (Wright et al.,Nature Genetics 2014)"=col_fun1,"M146_MHC-TLR7-TLR8 cluster"=col_fun2,"M47_M47.2_M69_enriched in B cells (I/III/VI)"=col_fun3,"S2_B cell surface signature"=col_fun4,"M5.0_regulation of antigen presentation and immune response"=col_fun5,"M37.0_immune activation - generic cluster"=col_fun6,"M7.2_M61_enriched in NK cells (I/II)"=col_fun7,"M37.1_enriched in neutrophils (I)"=col_fun8,"M7.0_enriched in T cells (I)"=col_fun9,"M7.1_T cell activation (I)"=col_fun10,"M16_TLR and inflammatory signaling"=col_fun11,"M32.1_platelet activation (II)"=col_fun12,"M5.1_T cell activation and signaling"=col_fun13,"M11_M118_enriched in monocytes (II/IV)"=col_fun14,"S4_Monocyte surface signature"=col_fun15,"M4.3_myeloid cell enriched receptors and transporters"=col_fun16,"M2.0_M2.1_extracellular matrix (I/II)"=col_fun17,"M4.0_cell cycle and transcription"=col_fun18,"M49_transcription regulation in cell development"=col_fun19)

vpars_h_c1<-vpars_h[p_annot_l$clusterid==1,]
p_annot_l_c1<-p_annot_l[p_annot_l$clusterid==1,]
vpars_h_c1<-vpars_h_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1<-p_annot_l_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1$clusterid<-NULL
mat = t(vpars_h_c1)
column_ha = HeatmapAnnotation(df = p_annot_l_c1, col = col_list, na_col = "black", show_legend = F, show_annotation_name=F)
h1<-Heatmap(mat, name = "scVES", top_annotation = column_ha, col = magma(100), cluster_columns=F, cluster_rows=F,show_column_names=F, column_title = "C1")

vpars_h_c1<-vpars_h[p_annot_l$clusterid==2,]
p_annot_l_c1<-p_annot_l[p_annot_l$clusterid==2,]
vpars_h_c1<-vpars_h_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1<-p_annot_l_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1$clusterid<-NULL
mat = t(vpars_h_c1)
column_ha = HeatmapAnnotation(df = p_annot_l_c1, col = col_list, na_col = "black", show_legend = F, show_annotation_name=F)
h2<-Heatmap(mat, name = "scVES", top_annotation = column_ha, col = magma(100), cluster_columns=F, cluster_rows=F,show_column_names=F, column_title = "C2")

vpars_h_c1<-vpars_h[p_annot_l$clusterid==3,]
p_annot_l_c1<-p_annot_l[p_annot_l$clusterid==3,]
vpars_h_c1<-vpars_h_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1<-p_annot_l_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1$clusterid<-NULL
mat = t(vpars_h_c1)
column_ha = HeatmapAnnotation(df = p_annot_l_c1, col = col_list, na_col = "black", show_legend = F, show_annotation_name=F)
h3<-Heatmap(mat, name = "scVES", top_annotation = column_ha, col = magma(100), cluster_columns=F, cluster_rows=F,show_column_names=F, column_title = "C3")

vpars_h_c1<-vpars_h[p_annot_l$clusterid==4,]
p_annot_l_c1<-p_annot_l[p_annot_l$clusterid==4,]
vpars_h_c1<-vpars_h_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1<-p_annot_l_c1[order(p_annot_l_c1$"HERITABILITY (continuous h2 value)", decreasing = T),]
p_annot_l_c1$clusterid<-NULL
mat = t(vpars_h_c1)
column_ha = HeatmapAnnotation(df = p_annot_l_c1, col = col_list, na_col = "black", show_legend = F)
h4<-Heatmap(mat, name = "scVES", top_annotation = column_ha, col = magma(100), cluster_columns=F, cluster_rows=F,show_column_names=F, column_title = "C4")

h1+h2+h3+h4
```

```{r}
#visualize variance partitioning for top40 genes per main cluster
p_annot_l$clusterid<-cutree(p$tree_col, k = 4)[rownames(vpars_h)]

#var_b (Bcell dominated cluster)
var_b<-vpars[vpars$gene %in% row.names(p_annot_l[which(p_annot_l$clusterid==4),]),]
var_b<-var_b %>% group_by(gene) %>% dplyr::slice(which.max(subject_variance_explained)) %>% as.data.frame()
var_b<-head(var_b[order(var_b$subject_variance_explained, decreasing = T),],40)
colnames(var_b)<-c("batch","Subject","Sex","Residuals","Age","celltype","gene")
var_b<-reshape2::melt(var_b[c("Subject","Sex","Residuals","Age","gene")])
scale_df<-as.data.frame(var_b %>% group_by(gene) %>% summarize(scalefactor=1/sum(value)))
var_b<-merge(var_b,scale_df,)
var_b$value<-var_b$value*var_b$scalefactor
var_b_subj<-var_b[var_b$variable=="Subject",]
var_b_subj<-var_b_subj[order(var_b_subj$value, decreasing = T),]
var_b<-rbind(var_b_subj,var_b[var_b$variable!="Subject",])
var_b$variable<-factor(var_b$variable,levels=c("Residuals","Age","Sex","Subject"))
p2<-ggplot(data=var_b,aes(y=gene,x=value,group=variable,fill=variable))+geom_bar(stat='identity',colour="black",size=0.25)+scale_y_discrete(limits = rev(head(var_b,40)$gene)) + theme_classic() + labs(title="Bcells") + scale_fill_manual(values=c("white","#619CFF","#00BA38","#F8766D")) 

var_b$heritability<-NA
var_b$heritability[which(var_b$gene %in% inh777)]<-1
p1 <- ggplot(var_b, aes(x = 0,  y = gene, size=factor(heritability), color="red")) +geom_point()+scale_y_discrete(limits = rev(head(var_b,40)$gene)) +theme_minimal() + theme(axis.text = element_blank(), axis.title = element_blank(),panel.grid = element_blank())
pp1<-(p2 + theme(legend.position="none") | p1 + theme(legend.position="none")) + plot_layout(widths = c(10, 1))


#var_t (Tcell dominated cluster)
var_t<-vpars[vpars$gene %in% row.names(p_annot_l[which(p_annot_l$clusterid==2),]),]
var_t<-var_t %>% group_by(gene) %>% dplyr::slice(which.max(subject_variance_explained)) %>% as.data.frame()
var_t<-head(var_t[order(var_t$subject_variance_explained, decreasing = T),],40)
colnames(var_t)<-c("batch","Subject","Sex","Residuals","Age","celltype","gene")
var_t<-reshape2::melt(var_t[c("Subject","Sex","Residuals","Age","gene")])
scale_df<-as.data.frame(var_t %>% group_by(gene) %>% summarize(scalefactor=1/sum(value)))
var_t<-merge(var_t,scale_df,)
var_t$value<-var_t$value*var_t$scalefactor
var_t_subj<-var_t[var_t$variable=="Subject",]
var_t_subj<-var_t_subj[order(var_t_subj$value, decreasing = T),]
var_t<-rbind(var_t_subj,var_t[var_t$variable!="Subject",])
var_t$variable<-factor(var_t$variable,levels=c("Residuals","Age","Sex","Subject"))
p2<-ggplot(data=var_t,aes(y=gene,x=value,group=variable,fill=variable))+geom_bar(stat='identity',colour="black",size=0.25)+scale_y_discrete(limits = rev(head(var_t,40)$gene)) + theme_classic() + labs(title="Tcells") + scale_fill_manual(values=c("white","#619CFF","#00BA38","#F8766D")) 

var_t$heritability<-NA
var_t$heritability[which(var_t$gene %in% inh777)]<-1
p1 <- ggplot(var_t, aes(x = 0,  y = gene, size=factor(heritability), color="red")) +geom_point()+scale_y_discrete(limits = rev(head(var_t,40)$gene)) +theme_minimal() + theme(axis.text = element_blank(), axis.title = element_blank(),panel.grid = element_blank())
pp2<-(p2 + theme(legend.position="none") | p1 + theme(legend.position="none")) + plot_layout(widths = c(10, 1))


#var_n (NKcell dominated cluster)
var_n<-vpars[vpars$gene %in% row.names(p_annot_l[which(p_annot_l$clusterid==3),]),]
var_n<-var_n %>% group_by(gene) %>% dplyr::slice(which.max(subject_variance_explained)) %>% as.data.frame()
var_n<-head(var_n[order(var_n$subject_variance_explained, decreasing = T),],40)
colnames(var_n)<-c("batch","Subject","Sex","Residuals","Age","celltype","gene")
var_n<-reshape2::melt(var_n[c("Subject","Sex","Residuals","Age","gene")])
scale_df<-as.data.frame(var_n %>% group_by(gene) %>% summarize(scalefactor=1/sum(value)))
var_n<-merge(var_n,scale_df,)
var_n$value<-var_n$value*var_n$scalefactor
var_n_subj<-var_n[var_n$variable=="Subject",]
var_n_subj<-var_n_subj[order(var_n_subj$value, decreasing = T),]
var_n<-rbind(var_n_subj,var_n[var_n$variable!="Subject",])
var_n$variable<-factor(var_n$variable,levels=c("Residuals","Age","Sex","Subject"))
p2<-ggplot(data=var_n,aes(y=gene,x=value,group=variable,fill=variable))+geom_bar(stat='identity',colour="black",size=0.25)+scale_y_discrete(limits = rev(head(var_n,40)$gene)) + theme_classic() + labs(title="C3") + scale_fill_manual(values=c("white","#619CFF","#00BA38","#F8766D")) 

var_n$heritability<-NA
var_n$heritability[which(var_n$gene %in% inh777)]<-1
p1 <- ggplot(var_n, aes(x = 0,  y = gene, size=factor(heritability), color="red")) +geom_point()+scale_y_discrete(limits = rev(head(var_n,40)$gene)) +theme_minimal() + theme(axis.text = element_blank(), axis.title = element_blank(),panel.grid = element_blank())
pp3<-(p2 + theme(legend.position="none") | p1 + theme(legend.position="none")) + plot_layout(widths = c(10, 1))


#var_m (Monocyte dominated cluster)
var_m<-vpars[vpars$gene %in% row.names(p_annot_l[which(p_annot_l$clusterid==1),]),]
var_m<-var_m %>% group_by(gene) %>% dplyr::slice(which.max(subject_variance_explained)) %>% as.data.frame()
var_m<-head(var_m[order(var_m$subject_variance_explained, decreasing = T),],40)
colnames(var_m)<-c("batch","Subject","Sex","Residuals","Age","celltype","gene")
var_m<-reshape2::melt(var_m[c("Subject","Sex","Residuals","Age","gene")])
scale_df<-as.data.frame(var_m %>% group_by(gene) %>% summarize(scalefactor=1/sum(value)))
var_m<-merge(var_m,scale_df,)
var_m$value<-var_m$value*var_m$scalefactor
var_m_subj<-var_m[var_m$variable=="Subject",]
var_m_subj<-var_m_subj[order(var_m_subj$value, decreasing = T),]
var_m<-rbind(var_m_subj,var_m[var_m$variable!="Subject",])
var_m$variable<-factor(var_m$variable,levels=c("Residuals","Age","Sex","Subject"))
p2<-ggplot(data=var_m,aes(y=gene,x=value,group=variable,fill=variable))+geom_bar(stat='identity',colour="black",size=0.25)+scale_y_discrete(limits = rev(head(var_m,40)$gene)) + theme_classic() + labs(title="Monocytes") + scale_fill_manual(values=c("white","#619CFF","#00BA38","#F8766D")) 

var_m$heritability<-NA
var_m$heritability[which(var_m$gene %in% inh777)]<-1
p1 <- ggplot(var_m, aes(x = 0,  y = gene, size=factor(heritability), color="red")) +geom_point()+scale_y_discrete(limits = rev(head(var_m,40)$gene)) +theme_minimal() + theme(axis.text = element_blank(), axis.title = element_blank(),panel.grid = element_blank())
pp4<-(p2 + theme(legend.position="none") | p1 + theme(legend.position="none")) + plot_layout(widths = c(10, 1))


p2
p1
pp1
pp2
pp3
pp4
```

```{r}
#visualize subject variance partitioning for selected immune response signatures

sigs<-ImmuneAgeStability::baseline_signatures[c("TGSig20","IHM","IFN","ia_bcell","iaa","GPR56highvslow_CD8_EM_sig","DE_CD29hi_CD8_genes")]
names(sigs)<-c("TGSig20","IHM","IFN","IAB B-cell","IAA","CD8 VM GPR56hi","CD8 VM CD29hi")
multisignature_stability_df<-ImmuneAgeStability::compute_multisignature_stability(sigs)
ImmuneAgeStability::plot_signature_stability_heatmap(multisignature_stability_df)
```


```{r}
#visualize subject variance time trends for selected immune response signature

stability_slope_df<-ImmuneAgeStability::compute_signature_stability_slope(signature_name = "IAB-Bcell", signature = ImmuneAgeStability::baseline_signatures$ia_bcell)
ImmuneAgeStability::plot_signature_stability_bars(stability_slope_df)
```
